### PR TITLE
Fixed the setup.sh script so that everything installs on MacOS. 

### LINKED ISSUE #34: Officially support making a development install on macOS
The primary issue is that `libunicorn.dylib` cannot load `libpyvex.dylib` on macOS. Possible solutions are:

- Setting `rpath` to `$ORIGIN`. Thanks @dfraze for this suggestion (if it works).
- Running `install_name_tool` on libunicorn.dylib as suggested in [this issue](https://github.com/angr/angr/issues/234).

### PR DESCRIPTION
**Pull request by adamdoupe**
Only tested on Mojave (10.14). 

- Checks that bash version 4.0 or greater is installed, outputs how to install on homebrew. 
- Installs all homebrew packages (if requested).

Fixes #34.

### CODE REVIEW

File: setup.sh [hunk 1]
```diff
@@ -30,7 +30,24 @@ function usage
...
 
+# We must do this check before the `declare`, because MacOS ships with bash version 3
+[ "$(uname)" == "Darwin" ] && IS_MACOS=1 || IS_MACOS=0
+
+if ((BASH_VERSINFO[0] < 4));
+then
+	echo "This script requires bash version >= 4.0, and you have bash verison $BASH_VERSION." >&2
+	if [ $IS_MACOS -eq 1 ];
+	then
+		echo -e "To install a newer bash version, use homebrew https://brew.sh/:\nbrew install bash\nYou don't need to link it or change the shell, it just needs to be installed." >&2
```
Comment (rhelmot) [inline setup.sh]: Should we just do this automatically if the -i flat is present?

File: setup.sh [hunk 2]
```diff
@@ -185,16 +203,34 @@ then
...
 
 info "Checking dependencies..."
-[ -e /etc/debian_version ] && [ $(dpkg --get-selections $DEBS | wc -l) -ne $(echo $DEBS | wc -w) ] && error "Please install the following packages: $DEBS" && exit 1
-[ -e /etc/pacman.conf ] && [ $(pacman -Qi $ARCHDEBS  2>&1 | grep "was not found" | wc -l) -ne 0 ] && error "Please install the following packages: $ARCHDEBS" && exit 1
-[ -e /etc/pacman.conf ] && [ $(pacman -Qi $ARCHCOMDEBS  2>&1 | grep "was not found" | wc -l) -ne 0 ] && error "Please install the following packages from AUR (yaourt -S <package_name>)): $ARCHCOMDEBS" && exit 1
-[ ! -e /etc/debian_version ] && [ ! -e /etc/pacman.conf ] && warning -e "WARNING: make sure you have dependencies installed.\nThe debian equivalents are: $DEBS.\nPress enter to continue." && read a
+if [ -e /etc/debian_version ]
+then
+	[ $(dpkg --get-selections $DEBS | wc -l) -ne $(echo $DEBS | wc -w) ] && error "Please install the following packages: $DEBS"
+elif [ -e /etc/pacman.conf ]
```
Comment (rhelmot) [inline setup.sh]: this isn't if-elif - there's two arch clauses that both need to run. you could make it into if-elif by merging them, though

File: setup.sh [hunk 3]
```diff
@@ -401,27 +437,51 @@ then
...
 	TO_INSTALL=${TO_INSTALL// angr-management/}
 	info "Install list: $TO_INSTALL"
 	[ -n "$TRAVIS" ] && TO_INSTALL=${TO_INSTALL// angr-management/}
 
-    	for PACKAGE in $TO_INSTALL; do
-            	info "Installing $PACKAGE."
-            	[ -n "${EXTRA_DEPS[$PACKAGE]}" ] && pip_install ${EXTRA_DEPS[$PACKAGE]}
-            	pip_install -e $PACKAGE
-    	done
+    for PACKAGE in $TO_INSTALL
```
Comment (rhelmot) [inline setup.sh]: why is this deindented

File: setup.sh (hunk 1 above)
Comment (adamdoupe) [reply setup.sh]: Probably, and I think I could get that to work, but I'd need to do a similar `homebrew` check here.

Perhaps I'll put the homebrew check into a function so that I can call it in both places.

File: setup.sh (hunk 2 above)
Comment (adamdoupe) [reply setup.sh]: Ohhhh, I see, thanks 👍

File: setup.sh (hunk 1 above)
Comment (adamdoupe) [reply setup.sh]: Actually, on second look, we can't put this check after the `declare`
https://github.com/angr/angr-dev/blob/master/setup.sh#L37

So we'd have to parse the `-i` flag earlier in the script. Probably not worth it IMHO.

File: setup.sh (hunk 3 above)
Comment (adamdoupe) [reply setup.sh]: Fixed, put it back to the original.

File: setup.sh (hunk 2 above)
Comment (adamdoupe) [reply setup.sh]: Collapsed the arch statements into one.
